### ISSUE TITLE
Error(s) in loading state_dict for CLIP

### ISSUE THREAD

**Issue by hannajiang** [BatsResearch/csp#1]
hello, I want to know how to solve this problem, size mismatch for positional_embedding: copying a param with shape torch.Size([77, 768]) from checkpoint, the shape in current model is torch.Size([8, 768]) when context_length=8; so should we set context_length=77? And we use a single NVIDIA RTX3090 to run this code, and  will occur the error cuda out of  memory.

**Comment by nihalnayak** [comment]
Thanks for posting this issue. You're right that setting the context_length=77 should solve this issue. But, as you point out, you may run into cuda out of memory error when you set the context_length=77 with your hardware.

Here's the snippet we used to adjust the context length. 

https://github.com/BatsResearch/csp/blob/e101091c1fcc2f8e66548e23766ba8b4bfed93f6/clip_modules/model_loader.py#L189-L198

Hope this helps!
