### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/feasibility_mit-states.pt'

### ISSUE THREAD

**Issue by AniketGurav** [BatsResearch/csp#12]
Hi, I have trained the model on mit-states using the command:

python -u train.py
--dataset mit-states
--clip_model ViT-L/14
--experiment_name csp
--seed 0
--epochs 20
--lr 5e-05
--attr_dropout 0.3
--weight_decay 0.00001
--train_batch_size 64
--gradient_accumulation_steps 2
--context_length 8
--save_path data/model/mit states/sample_model
--save_every_n 1

From the training section, I created a model called soft_embeddings_epoch_20.pt at location data/model/mit states/sample_model, and then training automatically stopped.

When I tried Closed-World Evaluation with the following command:

python -u evaluate.py
...

I got the following error:

Traceback (most recent call last):
File "evaluate.py", line 794, in <module>
unseen_scores = torch.load(
File "/home/aniket/csp/clone/lib/python3.8/site-packages/torch/serialization.py", line 791, in load
with _open_file_like(f, 'rb') as opened_file:
File "/home/aniket/csp/clone/lib/python3.8/site-packages/torch/serialization.py", line 271, in _open_file_like
return _open_file(name_or_buffer, mode)
File "/home/aniket/csp/clone/lib/python3.8/site-packages/torch/serialization.py", line 252, in init
super().init(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/aniket/csp/data/feasibility_mit-states.pt'

The code is expecting feasibility_mit-states.pt file. Can you please clarify the issue and upload the required file? Also, does this model file get created during training?

Thanks in advance.

**Comment by AniketGurav** [comment]
@nihalnayak 
Thanks, I am able to run python -u evaluate.py

**Comment by nihalnayak** [comment]
Awesome! Thank you.
