### ISSUE TITLE
 GPU memory 

### ISSUE THREAD

**Issue by Harzva** [BatsResearch/csp#14]
how much GPU memory is used for the experiments on the cgaq dataset?i can‘’t  do it，but can do on ut and mit.

**Comment by Harzva** [comment]
thank you very much

**Comment by nihalnayak** [comment]
You're right that C-GQA takes a lot more GPU memory to train the model. We used a single V100 GPU with 32GB memory. 

If you are running open-world evaluation with C-GQA, then you will need about 256GB of CPU memory as well. 

Hope this helps!

**Comment by Harzva** [comment]
I found that this task does not use multiple gpu training ，why? thank you very much.

**Comment by nihalnayak** [comment]
We were able fit the training on a single GPU for all the datasets. For that reason, we didn't invest time into multi-gpu training. But, CSP can be easily extended to multi-gpu training.
