### ISSUE TITLE
--context_length 8 size mismatch for positional_embedding

### ISSUE THREAD

**Issue by xugy16** [BatsResearch/csp#3]
Really apprecaite for your code.

Sorry for another question.

when i train the model using the suggested parameters.

I got an error.
size mismatch for positional_embedding, copying a param with shape torch.Size([77, 768]) from checkpoint, the shape in current model is torch.Size([8, 768]).

Maybe we should set --context_length to 77 not 8?

**Comment by nihalnayak** [comment]
Really appreciate you posting this issue. I just realized that I introduced a small bug while cleaning up the code. I have rectified the bug. 

Can you check if the code works for you?
