### ISSUE TITLE
Hyper-parameters about CoOp?

### ISSUE THREAD

**Issue by machengcheng2016** [BatsResearch/csp#5]
Love this work!
As for all the reported CoOp performances in your paper, I wonder how the hyper-parameters are set in your comparison experiments?

**Comment by nihalnayak** [comment]
Hi! We use the same hyperparameters for COOP and CSP in our experiments. You can find all the hyperparameters in Appendix B (see Table 5) of our [paper](https://arxiv.org/pdf/2204.03574.pdf).
