### ISSUE TITLE
Invalid download link

### ISSUE THREAD

**Issue by Cogito2012** [BatsResearch/csp#9]
Hi,

Thank you for sharing this gret work! The dataset download link [here](https://github.com/BatsResearch/csp/blob/a3997b0bb425260558407708167922d94ec1f04e/download_data.sh#L16) needs to be updated as [https://www.senthilpurushwalkam.com/publication/compositional/compositional_split_natural.tar.gz](https://www.senthilpurushwalkam.com/publication/compositional/compositional_split_natural.tar.gz). 

Besides, [this line](https://github.com/BatsResearch/csp/blob/a3997b0bb425260558407708167922d94ec1f04e/download_data.sh#L34) needs to be changed as `tar -zxvf compositional_split_natural.tar.gz`.

**Comment by nihalnayak** [comment]
Thank you for pointing out this issue. We will fix this bug immediately.
